Settings.alphabet.letters.c = "seek"
Settings.alphabet.letters.k = "kate"
Settings.alphabet.letters.l = "ella"
Settings.alphabet.letters.r = "rick"
Settings.alphabet.letters.t = "t"
Settings.alphabet.letters.x = "kex"
