Settings.alphabet.letters.c = "seek"
Settings.alphabet.letters.k = "kate"
Settings.alphabet.letters.l = "ella"
Settings.alphabet.letters.m = "emma"
Settings.alphabet.letters.r = "rick"
Settings.alphabet.letters.s = "s"
Settings.alphabet.letters.t = "teeth"
Settings.alphabet.letters.x = "rex"
