_.extend Settings.insert.abbreviations,
    error: 'err'
    address: 'addr'
    addresses: 'addrs'
    message: 'msg'
    parameter: 'param'
    response: 'res'
    userid: 'uid'
    username: 'uname'
